name: Grégory Lureau
title: Grégory Lureau
author: Grégory Lureau
email: gregorylureau@gmail.com
description:
  Some personnal Android developer notes.</br>
  Hope it can help or give you some fresh ideas ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://glureau.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: glureau
github_username:  glureau
permalink: pretty

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
#theme: jekyll-theme-terminal
theme: jekyll-theme-clean-blog
#theme: jekyll-theme-mdui
#theme: minima


assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock
  - repos/*
  - vendor/bundle

#ga_analytics: # Add Google Analytics tracking code

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

