title: Grégory Lureau
author: Grégory Lureau
email: gregorylureau@gmail.com
description:
  Some personnal Android developer notes.</br>
  Hope it can help or give you some fresh ideas ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: glureau
github_username:  glureau

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
#theme: jekyll-theme-terminal
theme: jekyll-theme-clean-blog
#theme: jekyll-theme-mdui
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
    - repos